### ISSUE TITLE
Exceptions on join

### ISSUE THREAD

**Issue by PatrLind** [rafzi/WAMP_POCO#1]
I was getting exceptions on row 449->451 because salt and iterations was empty.
I'm not sure if this is a correct solution, but I added some exception handling otherwise I could not join the realm.

```
        std::string salt;
        int iterations = 0;
        std::string challenge;
        try {
            salt = static_cast<std::string>(extra["salt"]);
        }
        catch (...){}
        try {
            iterations = extra["iterations"];
        }
        catch (...){}
        try {
            challenge = static_cast<std::string>(extra["challenge"]);
        }
        catch (...){}
```

**Comment by rafzi** [comment]
Thanks for pointing this out. I did not notice that salting in wampcra is optional.

Is the code doing the right thing with your changes, though? I'm not sure whether the password should be converted to base64 before signing it.

The spec suggests that it should not:

> The client needs to compute the signature as follows:
> signature := HMAC[SHA256]_{secret} (challenge)

**Comment by PatrLind** [comment]
No, I still had problems authenticating to the server unfortunately. I tried some variations on passwords, keys, iterations, etc. bu the server didn't like it. I can authenticate with other clients so there must be some other problem in the code. I used the ticket authentication instead, that works fine.
