### ISSUE TITLE
example issue

### ISSUE THREAD

**Issue by ghost** [rafzi/WAMP_POCO#2]
Hi all,
I'm working on a C++ Client for WAMP protocol and I need to use WebSocket connection; so I'd like to use WAMP POCO implementation.
In order to test this client I'm trying to use example_poco but it's seems to fail.
The error is related to the declaration of autobahn session.
In main.cpp the declaration includes SocketReactor parameter (autobahn::session ws(reactor)) but constructor in authobahnh doesn't accept any parameters. 
However using the correct form of constructor (autobahn::session ws() ), make failed with these kind of errors:

error: request for member ‘start’ in ‘ws’, which is of non-class type ‘autobahn::session()’
         if (!ws.start(Poco::Net::SocketAddress("localhost", 8080)))
                 ^
error: request for member ‘join’ in ‘ws’, which is of non-class type ‘autobahn::session()’
         ws.join("realm1", "wampcra", "peter", "secret1").get();
            ^
error: request for member ‘call’ in ‘ws’, which is of non-class type ‘autobahn::session()’
         auto result = ws.call("com.example.add2", {2, 3}).get();

Any suggestions?
Thanks to all, in advance.
Sincerely,
F.C.

**Comment by rafzi** [comment]
Thanks for the notice, I did forget to update the example after doing changes. It should be compiling fine now.

Note that with `autobahn::session ws();` you declare a function in C++. Omit the parenthesis to use a constructor without arguments.
