### ISSUE TITLE
autobahn.cpp:79: error: C2664: 'Poco::Net::Context::Context(const Poco::Net::Context &)': cannot convert argument 5 from 'bool' to 'const std::string &'

### ISSUE THREAD

**Issue by xgdgsc** [rafzi/WAMP_POCO#3]
Thanks for your work! I' ve tested this library with master head on linux and it compiles and works after removing `#include "util/make_unique.h"`. But on windows 10 with vs 2015, I get the following error:

```
autobahn.cpp:79: error: C2664: 'Poco::Net::Context::Context(const Poco::Net::Context &)': cannot convert argument 5 from 'bool' to 'const std::string &'
```

When I open the `Poco/Net/Context.h` file ( I installed Poco with `$ conan install Poco/1.7.5@lasote/stable`). I found the constructor of this really doesn' t exist. I don' t know how to fix this. Any clues?

**Comment by rafzi** [comment]
This library has been tested with POCO versions 1.5.4, 1.6.1 and 1.7.2. Version 1.7.5 also contains the constructor I'm using:

https://github.com/pocoproject/poco/blob/poco-1.7.5/NetSSL_OpenSSL/include/Poco/Net/Context.h#L190

On master it's still there.

Maybe an issue with that package manager? Cannot help you with that sorry.

**Comment by xgdgsc** [comment]
Thanks. It works with poco compiled by myself.
